import type { AuctionCardData, OrganizationCardData, CategoryCardData } from '@/types';

export interface DetailedAuction extends AuctionCardData {
  address: string;
  description: string;
  area: number;
  areaUnit: string;
  inspectionDate: string;
  contactOfficerName: string;
  contactOfficerPhone: string;
  contactOfficerEmail: string;
  terms: string;
  bidIncrement: string;
  images: string[];
  documents: {
    name: string;
    type: string;
    size: string;
    url: string;
  }[];
  organization: {
    name: string;
    slug: string;
    type: string;
    logo: string | null;
    phone: string;
    email: string;
    website: string;
  };
}

export const MOCK_ORGANIZATIONS: OrganizationCardData[] = [
  {
    id: 'org-sbi',
    name: 'State Bank of India',
    slug: 'sbi',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 342,
  },
  {
    id: 'org-pnb',
    name: 'Punjab National Bank',
    slug: 'pnb',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 218,
  },
  {
    id: 'org-bob',
    name: 'Bank of Baroda',
    slug: 'bob',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 189,
  },
  {
    id: 'org-canara',
    name: 'Canara Bank',
    slug: 'canara-bank',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 145,
  },
  {
    id: 'org-union',
    name: 'Union Bank of India',
    slug: 'union-bank',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 167,
  },
  {
    id: 'org-hdfc',
    name: 'HDFC Bank Ltd',
    slug: 'hdfc-bank',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 94,
  },
  {
    id: 'org-icici',
    name: 'ICICI Bank Ltd',
    slug: 'icici-bank',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 112,
  },
  {
    id: 'org-axis',
    name: 'Axis Bank Ltd',
    slug: 'axis-bank',
    type: 'BANK',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 88,
  },
  {
    id: 'org-omkara',
    name: 'Omkara Assets Reconstruction Pvt Ltd',
    slug: 'omkara-arc',
    type: 'ARC',
    logo: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 65,
  },
  {
    id: 'org-lichfl',
    name: 'LIC Housing Finance Ltd',
    slug: 'lichfl',
    type: 'HOUSING_FINANCE',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=120&auto=format&fit=crop&q=80',
    activeAuctionCount: 78,
  },
];

export const MOCK_CATEGORIES: CategoryCardData[] = [
  { name: 'Residential', slug: 'residential', type: 'RESIDENTIAL', icon: 'Home', auctionCount: 1420 },
  { name: 'Commercial', slug: 'commercial', type: 'COMMERCIAL', icon: 'Building2', auctionCount: 890 },
  { name: 'Industrial', slug: 'industrial', type: 'INDUSTRIAL', icon: 'Factory', auctionCount: 460 },
  { name: 'Agricultural', slug: 'agricultural', type: 'AGRICULTURAL', icon: 'Tractor', auctionCount: 310 },
  { name: 'Land / Plot', slug: 'land', type: 'LAND', icon: 'Map', auctionCount: 680 },
  { name: 'Other Assets', slug: 'other', type: 'OTHER', icon: 'Package', auctionCount: 195 },
];

export const MOCK_AUCTIONS: DetailedAuction[] = [
  {
    id: 'auc-101',
    auctionNumber: 'CA-MH-2026-101',
    title: '3 BHK Luxury Apartment in Lodha Bellissimo, Mahalaxmi',
    slug: '3-bhk-luxury-apartment-lodha-bellissimo-mahalaxmi-mumbai',
    categoryName: 'Residential Flat',
    categoryType: 'RESIDENTIAL',
    city: 'Mumbai',
    state: 'Maharashtra',
    organizationName: 'State Bank of India',
    organizationLogo: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=120&auto=format&fit=crop&q=80',
    reservePrice: '48500000',
    emd: '4850000',
    bidIncrement: '100000',
    startDateTime: new Date(Date.now() + 12 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 12 * 86400000 + 4 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 10 * 86400000).toISOString(),
    inspectionDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    auctionType: 'SARFAESI',
    status: 'UPCOMING',
    possessionStatus: 'PHYSICAL',
    primaryImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
    isFavourited: false,
    address: 'Flat No. 2402, 24th Floor, Tower B, Lodha Bellissimo, N.M. Joshi Marg, Mahalaxmi, Mumbai - 400011',
    description: 'All that piece and parcel of residential premises bearing Flat No. 2402 on the 24th floor, Tower B, admeasuring carpet area 1,680 sq.ft (built-up 2,150 sq.ft) with two covered stilt car parking spaces, together with undivided proportionate share in the common areas and land parcel.',
    area: 2150,
    areaUnit: 'sq ft',
    contactOfficerName: 'Mr. Rakesh Saxena (Chief Manager, SARB)',
    contactOfficerPhone: '+91-22-22741234',
    contactOfficerEmail: 'sarb.mumbai@sbi.co.in',
    terms: '1. The auction sale is conducted on "As is where is", "As is what is", and "Whatever there is" basis under Rule 8 & 9 of the Security Interest (Enforcement) Rules, 2002.\n2. Earnest Money Deposit (EMD) must be submitted via RTGS/NEFT/Online Payment Gateway prior to the deadline.\n3. The successful bidder must deposit 25% of the bid amount (inclusive of EMD) on the same or next business day.\n4. Balance 75% payable within 15 days.',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'SARFAESI Form IV Sale Notice', type: 'SALE_NOTICE', size: '1.4 MB', url: '#' },
      { name: 'Certified Title Search & Search Report', type: 'TITLE_DEED', size: '2.8 MB', url: '#' },
      { name: 'Tender Application & KYC Checklist', type: 'APPLICATION_FORM', size: '620 KB', url: '#' },
    ],
    organization: {
      name: 'State Bank of India',
      slug: 'sbi',
      type: 'BANK',
      logo: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=120&auto=format&fit=crop&q=80',
      phone: '+91-22-22740000',
      email: 'recovery@sbi.co.in',
      website: 'https://www.sbi.co.in',
    },
  },
  {
    id: 'auc-102',
    auctionNumber: 'CA-HR-2026-102',
    title: 'Grade-A Commercial Office in DLF Cyber City Phase II, Gurugram',
    slug: 'grade-a-commercial-office-dlf-cyber-city-gurugram',
    categoryName: 'Commercial Office',
    categoryType: 'COMMERCIAL',
    city: 'Gurugram',
    state: 'Haryana',
    organizationName: 'Punjab National Bank',
    organizationLogo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=120&auto=format&fit=crop&q=80',
    reservePrice: '32000000',
    emd: '3200000',
    bidIncrement: '50000',
    startDateTime: new Date(Date.now() + 1 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 1 * 86400000 + 3 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 4 * 3600000).toISOString(),
    inspectionDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    auctionType: 'SARFAESI',
    status: 'LIVE',
    possessionStatus: 'PHYSICAL',
    primaryImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&auto=format&fit=crop&q=80',
    isFavourited: true,
    address: 'Unit No. 504-506, 5th Floor, Building 10-C, DLF Cyber City, Phase-II, Gurugram, Haryana - 122002',
    description: 'Fully furnished commercial office space comprising 65 high-density workstations, 4 managerial cabins, 2 conference rooms, server room, and cafeteria. High rental yield potential in premier corporate hub.',
    area: 4200,
    areaUnit: 'sq ft',
    contactOfficerName: 'Ms. Sunita Bansal (AGM, Stressed Assets)',
    contactOfficerPhone: '+91-124-4112000',
    contactOfficerEmail: 'sarb.gurugram@pnb.co.in',
    terms: 'Strictly on "As is where is" basis. Minimum incremental bid: ₹50,000. Real-time auto extension active.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'SARFAESI Sale Notice', type: 'SALE_NOTICE', size: '1.2 MB', url: '#' },
      { name: 'Office Layout & Fire NOC', type: 'COMPLIANCE', size: '3.1 MB', url: '#' },
    ],
    organization: {
      name: 'Punjab National Bank',
      slug: 'pnb',
      type: 'BANK',
      logo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=120&auto=format&fit=crop&q=80',
      phone: '+91-11-28044000',
      email: 'eauction@pnb.co.in',
      website: 'https://www.pnbindia.in',
    },
  },
  {
    id: 'auc-103',
    auctionNumber: 'CA-KA-2026-103',
    title: 'Industrial Manufacturing Factory with Plant & Machinery, Peenya',
    slug: 'industrial-manufacturing-factory-peenya-bangalore',
    categoryName: 'Industrial Factory',
    categoryType: 'INDUSTRIAL',
    city: 'Bangalore',
    state: 'Karnataka',
    organizationName: 'Canara Bank',
    organizationLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
    reservePrice: '65000000',
    emd: '6500000',
    bidIncrement: '200000',
    startDateTime: new Date(Date.now() + 18 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 18 * 86400000 + 4 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 15 * 86400000).toISOString(),
    inspectionDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    auctionType: 'DRT',
    status: 'UPCOMING',
    possessionStatus: 'SYMBOLIC',
    primaryImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=900&auto=format&fit=crop&q=80',
    isFavourited: false,
    address: 'Plot No. 42-A & 43, 2nd Phase, Peenya Industrial Area, Bangalore North, Karnataka - 560058',
    description: 'Industrial land admeasuring 28,000 sq.ft along with built-up RCC industrial shed of 18,500 sq.ft, overhead 10T EOT crane, 250 KVA HT power connection, effluent treatment facility, and administrative block.',
    area: 28000,
    areaUnit: 'sq ft',
    contactOfficerName: 'Mr. K. Narayana Murthy (Recovery Officer, DRT Bangalore)',
    contactOfficerPhone: '+91-80-22123456',
    contactOfficerEmail: 'arm.bangalore@canarabank.com',
    terms: 'Conducted under Recovery of Debts and Bankruptcy Act through Debts Recovery Tribunal II Bangalore.',
    images: [
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'DRT Proclamation of Sale Notice', type: 'DRT_NOTICE', size: '2.1 MB', url: '#' },
      { name: 'Plant Machinery Valuation Report', type: 'VALUATION', size: '4.5 MB', url: '#' },
    ],
    organization: {
      name: 'Canara Bank',
      slug: 'canara-bank',
      type: 'BANK',
      logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
      phone: '+91-80-22221581',
      email: 'recovery@canarabank.com',
      website: 'https://canarabank.com',
    },
  },
  {
    id: 'auc-104',
    auctionNumber: 'CA-MH-2026-104',
    title: '4 BHK Independent Bungalow with Private Garden, Koregaon Park',
    slug: '4-bhk-independent-bungalow-koregaon-park-pune',
    categoryName: 'Bungalow / Villa',
    categoryType: 'RESIDENTIAL',
    city: 'Pune',
    state: 'Maharashtra',
    organizationName: 'Bank of Baroda',
    organizationLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    reservePrice: '72000000',
    emd: '7200000',
    bidIncrement: '200000',
    startDateTime: new Date(Date.now() + 21 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 21 * 86400000 + 4 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 18 * 86400000).toISOString(),
    inspectionDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    auctionType: 'SARFAESI',
    status: 'UPCOMING',
    possessionStatus: 'PHYSICAL',
    primaryImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&auto=format&fit=crop&q=80',
    isFavourited: false,
    address: 'Plot No. 18, Lane No. 5, Koregaon Park, Haveli Taluka, Pune, Maharashtra - 411001',
    description: 'Prime independent ground + 1 storey residential bungalow constructed on freehold NA plot admeasuring 500 sq. meters (5,382 sq.ft). Features landscaped garden, servant quarters, and 4-car parking portico.',
    area: 5400,
    areaUnit: 'sq ft',
    contactOfficerName: 'Mr. Deepak Chawla (Chief Manager)',
    contactOfficerPhone: '+91-20-26129876',
    contactOfficerEmail: 'sarb.pune@bankofbaroda.com',
    terms: 'Sold under physical possession by authorized officer under SARFAESI Act, 2002.',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'SARFAESI Form IV Sale Notice', type: 'SALE_NOTICE', size: '1.6 MB', url: '#' },
      { name: 'City Survey Extract (Property Card)', type: 'LAND_RECORD', size: '980 KB', url: '#' },
    ],
    organization: {
      name: 'Bank of Baroda',
      slug: 'bob',
      type: 'BANK',
      logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
      phone: '+91-22-66985000',
      email: 'sarfaesi@bankofbaroda.co.in',
      website: 'https://www.bankofbaroda.in',
    },
  },
  {
    id: 'auc-105',
    auctionNumber: 'CA-GJ-2026-105',
    title: 'Prime Retail Corner Showroom in CG Road, Navrangpura',
    slug: 'retail-corner-showroom-cg-road-navrangpura-ahmedabad',
    categoryName: 'Showroom',
    categoryType: 'COMMERCIAL',
    city: 'Ahmedabad',
    state: 'Gujarat',
    organizationName: 'Union Bank of India',
    organizationLogo: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=120&auto=format&fit=crop&q=80',
    reservePrice: '28000000',
    emd: '2800000',
    bidIncrement: '50000',
    startDateTime: new Date(Date.now() + 14 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 14 * 86400000 + 3 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 11 * 86400000).toISOString(),
    inspectionDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    auctionType: 'SARFAESI',
    status: 'UPCOMING',
    possessionStatus: 'PHYSICAL',
    primaryImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=900&auto=format&fit=crop&q=80',
    isFavourited: false,
    address: 'Shop No. G-1 & G-2, Ground Floor, Samarth Commercial Complex, C.G. Road, Ahmedabad - 380009',
    description: 'High visibility road-facing double height corner showroom with wide frontage on premier retail corridor C.G. Road. Suitable for flagship brand showroom, bank branch, jewelry store, or healthcare clinic.',
    area: 2600,
    areaUnit: 'sq ft',
    contactOfficerName: 'Mr. Bhavesh Patel (Authorized Officer)',
    contactOfficerPhone: '+91-79-26567890',
    contactOfficerEmail: 'sarb.ahmedabad@unionbankofindia.com',
    terms: 'As is where is basis. Clear encumbrance certificate issued by legal counsel.',
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'Public Auction Notice', type: 'SALE_NOTICE', size: '1.1 MB', url: '#' },
    ],
    organization: {
      name: 'Union Bank of India',
      slug: 'union-bank',
      type: 'BANK',
      logo: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=120&auto=format&fit=crop&q=80',
      phone: '+91-22-22892000',
      email: 'eauction@unionbankofindia.com',
      website: 'https://www.unionbankofindia.co.in',
    },
  },
  {
    id: 'auc-106',
    auctionNumber: 'CA-GJ-2026-106',
    title: 'Freehold Industrial Land Parcel in Sanand GIDC Phase II',
    slug: 'freehold-industrial-land-sanand-gidc-ahmedabad',
    categoryName: 'Industrial Plot',
    categoryType: 'LAND',
    city: 'Ahmedabad',
    state: 'Gujarat',
    organizationName: 'Omkara Assets Reconstruction Pvt Ltd',
    organizationLogo: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=120&auto=format&fit=crop&q=80',
    reservePrice: '45000000',
    emd: '4500000',
    bidIncrement: '100000',
    startDateTime: new Date(Date.now() + 25 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 25 * 86400000 + 4 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 22 * 86400000).toISOString(),
    inspectionDate: new Date(Date.now() + 16 * 86400000).toISOString(),
    auctionType: 'NPA',
    status: 'UPCOMING',
    possessionStatus: 'PHYSICAL',
    primaryImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&auto=format&fit=crop&q=80',
    isFavourited: false,
    address: 'Plot No. C-14, Sanand GIDC Phase-II, District Ahmedabad, Gujarat - 382110',
    description: 'Prime industrial plot located within Sanand Automobile & Engineering hub. Excellent highway connectivity to NH-8A, dedicated water connection, high-tension electric substation boundary line.',
    area: 82000,
    areaUnit: 'sq ft',
    contactOfficerName: 'Mr. Arvind Joshi (VP, NPA Resolution)',
    contactOfficerPhone: '+91-22-26544010',
    contactOfficerEmail: 'sanand.sales@omkaraarc.com',
    terms: 'NPA portfolio disposition by ARC under SARFAESI Act powers.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'GIDC Allotment & Transfer Clearance', type: 'GIDC_NOC', size: '2.4 MB', url: '#' },
    ],
    organization: {
      name: 'Omkara Assets Reconstruction Pvt Ltd',
      slug: 'omkara-arc',
      type: 'ARC',
      logo: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=120&auto=format&fit=crop&q=80',
      phone: '+91-22-26544000',
      email: 'contact@omkaraarc.com',
      website: 'https://www.omkaraarc.com',
    },
  },
  {
    id: 'auc-107',
    auctionNumber: 'CA-UP-2026-107',
    title: '2 BHK Affordable Residential Flat in Sector 75, Noida',
    slug: '2-bhk-affordable-flat-sector-75-noida',
    categoryName: 'Residential Flat',
    categoryType: 'RESIDENTIAL',
    city: 'Noida',
    state: 'Uttar Pradesh',
    organizationName: 'LIC Housing Finance Ltd',
    organizationLogo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=120&auto=format&fit=crop&q=80',
    reservePrice: '5800000',
    emd: '580000',
    bidIncrement: '25000',
    startDateTime: new Date(Date.now() + 8 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 8 * 86400000 + 2 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 6 * 86400000).toISOString(),
    inspectionDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    auctionType: 'SARFAESI',
    status: 'UPCOMING',
    possessionStatus: 'PHYSICAL',
    primaryImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80',
    isFavourited: false,
    address: 'Flat No. 602, 6th Floor, Tower Emerald, Golf City Society, Sector 75, Noida, UP - 201301',
    description: 'Well-maintained 2 BHK apartment near Sector 50 Metro Station. Club house, power backup, covered parking, gated security. Clean encumbrance certificate on record.',
    area: 1050,
    areaUnit: 'sq ft',
    contactOfficerName: 'Mr. Amitav Ray (Authorized Officer)',
    contactOfficerPhone: '+91-120-4321000',
    contactOfficerEmail: 'recovery.noida@lichousing.com',
    terms: 'SARFAESI sale under rule 8(6) and 9(1). Immediate key handover upon 100% remittance.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'Official Form IV Notice', type: 'SALE_NOTICE', size: '1.2 MB', url: '#' },
    ],
    organization: {
      name: 'LIC Housing Finance Ltd',
      slug: 'lichfl',
      type: 'HOUSING_FINANCE',
      logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=120&auto=format&fit=crop&q=80',
      phone: '+91-22-22178600',
      email: 'sarfaesi@lichousing.com',
      website: 'https://www.lichousing.com',
    },
  },
  {
    id: 'auc-108',
    auctionNumber: 'CA-KA-2026-108',
    title: 'Fertile Agricultural Farmland of 4.5 Acres near Devanahalli',
    slug: 'fertile-agricultural-farmland-devanahalli-bangalore-rural',
    categoryName: 'Agricultural Land',
    categoryType: 'AGRICULTURAL',
    city: 'Bangalore',
    state: 'Karnataka',
    organizationName: 'State Bank of India',
    organizationLogo: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=120&auto=format&fit=crop&q=80',
    reservePrice: '38000000',
    emd: '3800000',
    bidIncrement: '100000',
    startDateTime: new Date(Date.now() + 2 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 2 * 86400000 + 4 * 3600000).toISOString(),
    submissionDeadline: new Date(Date.now() + 1 * 86400000).toISOString(),
    inspectionDate: new Date(Date.now()).toISOString(),
    auctionType: 'SARFAESI',
    status: 'CLOSING_SOON',
    possessionStatus: 'PHYSICAL',
    primaryImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=900&auto=format&fit=crop&q=80',
    isFavourited: true,
    address: 'Sy. No. 84/2 & 84/3, Kundana Hobli, Devanahalli Taluk, Bangalore Rural District, Karnataka - 562110',
    description: 'Clear title agricultural red-soil land with 2 active borewells, motor pumpset, drip irrigation lines, and tar road approach. Just 18 km from Kempegowda International Airport.',
    area: 196020,
    areaUnit: 'sq ft',
    contactOfficerName: 'Mr. M. S. Venkatesh (AGM)',
    contactOfficerPhone: '+91-80-25987100',
    contactOfficerEmail: 'sarb.devanahalli@sbi.co.in',
    terms: 'Submission deadline closes in 24 hours. Bidders must hold eligible agricultural registration or status.',
    images: [
      'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=900&auto=format&fit=crop&q=80',
    ],
    documents: [
      { name: 'RTC / Pahani Land Records', type: 'LAND_RECORD', size: '2.1 MB', url: '#' },
      { name: 'Tender Form & Bidder Manual', type: 'APPLICATION_FORM', size: '750 KB', url: '#' },
    ],
    organization: {
      name: 'State Bank of India',
      slug: 'sbi',
      type: 'BANK',
      logo: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=120&auto=format&fit=crop&q=80',
      phone: '+91-22-22740000',
      email: 'recovery@sbi.co.in',
      website: 'https://www.sbi.co.in',
    },
  },
];
